"use client";

import { useState, useMemo } from "react";

import styles from "./app-shell.module.css";
import { useCithai } from "./cithai-context";
import { CompassIcon } from "./icons";
import { TrackCard } from "./track-card";

type SortKey = "newest" | "oldest" | "title_asc" | "title_desc";

function BrowseMetric({ label, value }: { label: string; value: number }) {
  return (
    <div className={styles.metricCard}>
      <span>{label}</span>
      <strong>{String(value).padStart(2, "0")}</strong>
    </div>
  );
}

export function BrowsePage() {
  const {
    activeSong,
    isLoading,
    browseSongs,
    setActiveSongId,
    playSong,
    shareSong,
    getUserName,
  } = useCithai();
  const [searchQuery, setSearchQuery] = useState("");
  const [sortBy, setSortBy] = useState<SortKey>("newest");

  const filteredSongs = useMemo(() => {
    let result = browseSongs;

    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter((song) => song.title.toLowerCase().includes(q));
    }

    return result.sort((a, b) => {
      if (sortBy === "newest") {
        return new Date(b.creation_date).getTime() - new Date(a.creation_date).getTime();
      }
      if (sortBy === "oldest") {
        return new Date(a.creation_date).getTime() - new Date(b.creation_date).getTime();
      }
      if (sortBy === "title_asc") {
        return a.title.localeCompare(b.title);
      }
      if (sortBy === "title_desc") {
        return b.title.localeCompare(a.title);
      }
      return 0;
    });
  }, [browseSongs, searchQuery, sortBy]);

  return (
    <div className={styles.pageStack}>
      <section className={styles.pageHeaderPanel}>
        <div>
          <p className={styles.eyebrow}>Browse</p>
          <h2 className={styles.sectionTitle}>Discover new music</h2>
          <p className={styles.pageText}>
            Listen to public tracks generated by the community.
          </p>
        </div>
        <div className={styles.metricRow}>
          <BrowseMetric label="Public Tracks" value={browseSongs.length} />
        </div>
      </section>

      <section className={styles.panel}>
        <div className={styles.panelHeader}>
          <div>
            <p className={styles.eyebrow}>Platform</p>
            <h3 className={styles.sectionTitle}>All Public Songs</h3>
          </div>
          <div className={styles.toolbar}>
            <input
              type="text"
              placeholder="Search songs..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className={styles.input}
              style={{ minHeight: "42px", flex: 1, padding: "0 12px" }}
            />
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as SortKey)}
              className={styles.select}
              style={{ minHeight: "42px", flexShrink: 0, width: "auto", padding: "0 12px" }}
            >
              <option value="newest">Sort: Newest</option>
              <option value="oldest">Sort: Oldest</option>
              <option value="title_asc">Sort: Title (A-Z)</option>
              <option value="title_desc">Sort: Title (Z-A)</option>
            </select>
          </div>
        </div>

        {isLoading ? (
          <div className={styles.emptyState}>
            <div className={styles.spinner} />
            <p>Loading community tracks...</p>
          </div>
        ) : filteredSongs.length ? (
          <div className={styles.songGrid}>
            {filteredSongs.map((song, index) => (
              <TrackCard
                key={song.id}
                song={song}
                index={index}
                isActive={activeSong?.id === song.id}
                onSelect={setActiveSongId}
                onPlay={playSong}
                showStatus={false}
                onShare={shareSong}
                subtitle={`By ${getUserName(song.user_id)}`}
              />
            ))}
          </div>
        ) : (
          <div className={styles.emptyState}>
            <CompassIcon />
            <p>No public songs available matching this search.</p>
          </div>
        )}
      </section>
    </div>
  );
}
