import { BrowsePage } from "@/components/browse-page";

export const metadata = {
  title: "Browse | Cithai",
  description: "Discover public tracks generated by the community.",
};

export default function Page() {
  return <BrowsePage />;
}
