# Generated by Django 6.0.3 on 2026-03-23 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('custom_lyrics', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ROMANTIC', 'Romantic'), ('ENERGETIC', 'Energetic'), ('CALM', 'Calm')], max_length=20)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('HIPHOP', 'HipHop')], max_length=20)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('GRADUATION', 'Graduation'), ('ANNIVERSARY', 'Anniversary'), ('CUSTOM', 'Custom')], max_length=20)),
                ('voice_type', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('CHILD', 'Child'), ('CHOIR', 'Choir'), ('INSTRUMENTAL', 'Instrumental'), ('DUET', 'Duet')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_retry', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('custom_lyrics', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('audio_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ROMANTIC', 'Romantic'), ('ENERGETIC', 'Energetic'), ('CALM', 'Calm')], max_length=20)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('HIPHOP', 'HipHop')], max_length=20)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('GRADUATION', 'Graduation'), ('ANNIVERSARY', 'Anniversary'), ('CUSTOM', 'Custom')], max_length=20)),
                ('voice_type', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('CHILD', 'Child'), ('CHOIR', 'Choir'), ('INSTRUMENTAL', 'Instrumental'), ('DUET', 'Duet')], max_length=20)),
                ('generation_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song', to='songs.musicgenerationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.user')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='songs.song')),
            ],
        ),
        migrations.AddField(
            model_name='musicgenerationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='songs.user'),
        ),
    ]
