# Generated by Django 5.2.8 on 2026-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_generationjob_song_generation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
